/var/spool/pbs/mom_priv/jobs/13875.pbs-7.SC: line 27: ./logs/update_venv.log: No such file or directory
Features: ['LOLA', 'Diviner', 'M3', 'MiniRF']
Input dimension: 4
Entering training loop after 190.07 seconds
Traceback (most recent call last):
  File "/rds/general/user/as5023/home/irp-as5023/model/model_scripts/../src/trainFCNN.py", line 135, in <module>
    if __name__ == '__main__':
        ^^^^^^
  File "/rds/general/user/as5023/home/irp-as5023/model/model_scripts/../src/trainFCNN.py", line 122, in main
    train(args)
  File "/rds/general/user/as5023/home/irp-as5023/model/model_scripts/../src/trainFCNN.py", line 96, in train
    val_loss, val_mse, val_r2 = validate(device, model, criterion, test_loader)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/as5023/home/irp-as5023/model/src/evaluate.py", line 22, in validate
    inputs, targets = inputs.to(device), targets.to(device)
                      ^^^^^^
UnboundLocalError: cannot access local variable 'inputs' where it is not associated with a value
Completed on Sun 11 Aug 13:40:21 BST 2024

====================================
CPU Time used: 04:36:56
CPU Percent: 98%
Memory usage: 37198088kb
Approx Power usage: 0.0552
Walltime usage: 04:40:02

====================================
